### ISSUE TITLE
Missing DATE_TIME-plot when executing bp_ts_plot()

### ISSUE THREAD

**Issue by ataraxs** [johnschwenck/bp#12]
First: Many thanks for this great package!
Just tried it with some own values, and received a perfect bp-Report ( bp_report() ). As I used the bp_ts_plots() function it only resulted in the BP-by-hour-plot, omitting the the BP-by-DATE_TIME-plot (for a series of >150 values from approx. a month's period). Perhaps my fault (as I didn't have read the complete manual, just the vignette) or some issue?
Keep up your great work!

**Comment by ataraxs** [comment]
typo: It should have been written and read bp_ts_plots()

**Comment by mahmutoezmen** [comment]
Have you navigated between the plots using left and right arrows? You should use the left and right arrows which is just under 'Plots' options to navigate between the plots. There are 4 plots popping up when using the following code

``bp_ts_plots(hypnos_proc, first_hour = 11,wrap_var = 'visit',subj = c('70435', '70439') )``

**Comment by ataraxs** [comment]
Many thanks for your fast reply. You are right. I didn't pay attention to those navigation knobs. So, everything works fine. Best regards.
