### ISSUE TITLE
bp_hist() with bp_children and bp_preg data

### ISSUE THREAD

**Issue by dmaywald** [johnschwenck/bp#3]
with the bp_children data processed such as 

`children_proc <- process_data(bp_children, 
                                  sbp = 'sbp', dbp = 'dbp',
                                  id = 'id', visit = 'visit)` 

and run the bp_hist() function 

`bp_hist(children_proc)`

I get the following error...
`Error in eval(predvars, data, env) : object 'DAY_OF_WEEK' not found`

**Comment by johnschwenck** [comment]
This should be fixed now. Can you use the most recent version of bp and try again before I close this issue?
