### ISSUE TITLE
bp_scatter() subj parameter does not behave as expected

### ISSUE THREAD

**Issue by dmaywald** [johnschwenck/bp#4]
I have the bp_hypnos data processed such as...

`
hypnos_proc <- process_data(bp_hypnos,
                            bp_type = 'abpm',
                            sbp = "syst",
                            dbp = "DIAST",
                            date_time = "date.time",
                            id = "id",
                            wake = "wake",
                            visit = "visit",
                            hr = "hr",
                            map = "map",
                            rpp = "rpp",
                            pp = "pp",
                            ToD_int = c(5, 13, 18, 23))
`

We have the following different ID's we can use in the subj argument of the bp_scatter function...
`70417, 70422, 70424, 70435,70439`

When running the code with all the subjects selected `bp_scatter(data = hypnos_proc, subj = c(70417, 70422, 70424, 70435,70439))` and none of the subjects selected `bp_scatter(data = hypnos_proc, subj = NULL)`, I would expect the same plot to be produced, but this is not the case.

Moreover, the following warning occurs,
`Warning message:
In ID == subj :
  longer object length is not a multiple of shorter object length`
but this only happens when more than 2 subjects are selected, that is `bp_scatter(data = hypnos_proc, subj = c(70424, 70435))` would not produce the warning, but `bp_scatter(data = hypnos_proc, subj = c(70424, 70435, 70439))` would produce the warning.

**Comment by irinagain** [comment]
I believe this is fixed now. Please let me know if you can confirm
